AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  StripeSecretKey:
    Type: String
    Description: Stripe Secret Key
Resources:
  PaymentApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.payment.main.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: s3://payment-system-sam/a8cce3ebf82b61389351a7add3fa9eea
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          STRIPE_SECRET_KEY:
            Ref: StripeSecretKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      SamResourceId: PaymentApiFunction
